spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/checkpass
    username: postgres
    password: shin
  #Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
